### ISSUE TITLE
could you add a license

### ISSUE THREAD

**Issue by electrolys** [eloraiby/c99-3d-math#1]
turns out i'm not allowed to use this if you don't have a license saying that i can so could you please add a license

**Comment by eloraiby** [comment]
The licence is GPL v3 with the runtime library exception:
* You can link it with your program (static/dynamic), but no need to distribute the source code of your specific program code
* You need to only distribute the source code of your modifications/bug fixes to this library

It's a win-win for everyone: you get to use it in a commercial program (you will keep the source code of your program closed), and everyone get the bug fixes if there are any! :

```
/*
** 3D math library Copyright 2015(c) Wael El Oraiby. All Rights Reserved
**
** This library is distributed in the hope that it will be useful,
** but WITHOUT ANY WARRANTY; without even the implied warranty of
** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
** GNU General Public License for more details.
**
** Under Section 7 of GPL version 3, you are granted additional
** permissions described in the GCC Runtime Library Exception, version
** 3.1, as published by the Free Software Foundation.
**
** You should have received a copy of the GNU General Public License and
** a copy of the GCC Runtime Library Exception along with this program;
** see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see
** <http://www.gnu.org/licenses/>.
**
*/
```

**Comment by electrolys** [comment]
thanks
